// Plain, dialect-boring SQL so the connector can later be swapped for Postgres.
// IDs (crypto.randomUUID) and created_at (ISO string) are generated by the app.
const SCHEMA = `
CREATE TABLE IF NOT EXISTS events (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  admin_key TEXT NOT NULL,
  questionnaire TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS participants (
  id TEXT PRIMARY KEY,
  event_id TEXT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  answers TEXT NOT NULL,
  title TEXT,
  tagline TEXT,
  emoji TEXT,
  ai_status TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS participants_event_id ON participants (event_id);

CREATE TABLE IF NOT EXISTS rounds (
  id TEXT PRIMARY KEY,
  event_id TEXT NOT NULL,
  number INTEGER NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  UNIQUE (event_id, number)
);

CREATE TABLE IF NOT EXISTS pairs (
  id TEXT PRIMARY KEY,
  round_id TEXT NOT NULL,
  participant_ids TEXT NOT NULL,
  reason TEXT NOT NULL,
  icebreaker TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS pairs_round_id ON pairs (round_id);
`

let schemaReady: Promise<void> | undefined

// Memoized: Nitro doesn't await async plugins, so handlers await this too.
// A failed attempt is forgotten so the next call retries.
export function ensureSchema() {
  schemaReady ??= useDatabase().exec(SCHEMA)
    .then(() => {})
    .catch((error) => {
      schemaReady = undefined
      throw error
    })
  return schemaReady
}

// Always use this instead of useDatabase() directly.
export async function useDb() {
  await ensureSchema()
  return useDatabase()
}
